// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	admin "forum/app/community/api/internal/handler/admin"
	public "forum/app/community/api/internal/handler/public"
	"forum/app/community/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// create a new community
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: admin.CreateCommunityHandler(serverCtx),
			},
			{
				// update community details
				Method:  http.MethodPost,
				Path:    "/update/:id",
				Handler: admin.UpdateCommunityHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/community/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// get all communities
				Method:  http.MethodGet,
				Path:    "/all",
				Handler: public.GetAllCommunitiesHandler(serverCtx),
			},
			{
				// get community details
				Method:  http.MethodGet,
				Path:    "/details/:id",
				Handler: public.GetCommunityDetailsHandler(serverCtx),
			},
			{
				// get all posts in a community
				Method:  http.MethodGet,
				Path:    "/posts/:id",
				Handler: public.GetCommunityPostsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/community/v1"),
	)
}
