// Code generated by goctl. DO NOT EDIT.
// Source: community.proto

package server

import (
	"context"

	"forum/app/community/rpc/internal/logic"
	"forum/app/community/rpc/internal/svc"
	"forum/app/community/rpc/pb"
)

type CommunityServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCommunityServiceServer
}

func NewCommunityServiceServer(svcCtx *svc.ServiceContext) *CommunityServiceServer {
	return &CommunityServiceServer{
		svcCtx: svcCtx,
	}
}

// Public endpoints
func (s *CommunityServiceServer) GetAllCommunities(ctx context.Context, in *pb.GetAllCommunitiesRequest) (*pb.GetAllCommunitiesResponse, error) {
	l := logic.NewGetAllCommunitiesLogic(ctx, s.svcCtx)
	return l.GetAllCommunities(in)
}

func (s *CommunityServiceServer) GetCommunityDetails(ctx context.Context, in *pb.GetCommunityDetailsRequest) (*pb.GetCommunityDetailsResponse, error) {
	l := logic.NewGetCommunityDetailsLogic(ctx, s.svcCtx)
	return l.GetCommunityDetails(in)
}

func (s *CommunityServiceServer) GetCommunityPosts(ctx context.Context, in *pb.GetCommunityPostsRequest) (*pb.GetCommunityPostsResponse, error) {
	l := logic.NewGetCommunityPostsLogic(ctx, s.svcCtx)
	return l.GetCommunityPosts(in)
}

// Admin endpoints
func (s *CommunityServiceServer) UpdateCommunity(ctx context.Context, in *pb.UpdateCommunityRequest) (*pb.UpdateCommunityResponse, error) {
	l := logic.NewUpdateCommunityLogic(ctx, s.svcCtx)
	return l.UpdateCommunity(in)
}

func (s *CommunityServiceServer) CreateCommunity(ctx context.Context, in *pb.CreateCommunityRequest) (*pb.CreateCommunityResponse, error) {
	l := logic.NewCreateCommunityLogic(ctx, s.svcCtx)
	return l.CreateCommunity(in)
}
