// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	comment "forum/app/comment/api/internal/handler/comment"
	"forum/app/comment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建评论
				Method:  http.MethodPost,
				Path:    "/comments",
				Handler: comment.CreateCommentHandler(serverCtx),
			},
			{
				// 删除评论
				Method:  http.MethodDelete,
				Path:    "/comments/:commentId",
				Handler: comment.DeleteCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/comment/v1"),
	)
}
