// Code generated by goctl. DO NOT EDIT.
package types

type AuthorInfo struct {
	UserId       int64  `json:"userId"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	Phone        string `json:"phone,optional"`
	City         string `json:"city,optional"`
	Introduction string `json:"introduction,optional"`
	Avatar       string `json:"avatar,optional"`
}

type Comment struct {
	CommentId   int64  `json:"commentId"`   // 评论ID
	PostId      int64  `json:"postId"`      // 所属帖子ID
	AuthorId    int64  `json:"authorId"`    // 作者ID
	Content     string `json:"content"`     // 评论内容
	CreateTime  string `json:"createTime"`  // 创建时间
	UpdatedTime string `json:"updatedTime"` // 更新时间
}

type Community struct {
	CommunityId   int64  `json:"communityId"`
	CommunityName string `json:"communityName"`
	Introduction  string `json:"introduction,omitempty"`
	CreateTime    string `json:"createTime"`
	UpdatedTime   string `json:"updatedTime"`
}

type CreatePostReq struct {
	CommunityId int64  `json:"communityId"` // 社区ID
	Title       string `json:"title"`       // 帖子标题
	Content     string `json:"content"`     // 帖子内容
}

type CreatePostResp struct {
	PostId int64 `json:"postId"` // 创建的帖子ID
}

type DeletePostReq struct {
	PostId int64 `path:"postId"` // 要删除的帖子ID
}

type DeletePostResp struct {
}

type GetCommentListReq struct {
	PostId   int64 `path:"postId"`                       // 帖子ID
	Page     int64 `form:"page,optional,default=1"`      // 页码
	PageSize int64 `form:"pageSize,optional,default=10"` // 每页数量
}

type GetCommentListResp struct {
	Total    int64     `json:"total"`    // 总评论数
	Comments []Comment `json:"comments"` // 评论列表
}

type GetPostDetailReq struct {
	PostId int64 `path:"postId"` // 帖子ID
}

type GetPostDetailResp struct {
	PostDetail PostDetail `json:"PostDetail"`
}

type GetPostListReq struct {
	Page        int64 `form:"page,optional,default=1"`      // 页码
	PageSize    int64 `form:"pageSize,optional,default=10"` // 每页数量
	CommunityId int64 `form:"communityId,optional"`         // 按社区筛选
	AuthorId    int64 `form:"authorId,optional"`            // 按作者筛选
}

type GetPostListResp struct {
	Total int64        `json:"total"` // 总帖子数
	Posts []PostDetail `json:"posts"` // 帖子列表
}

type Post struct {
	PostId      int64  `json:"postId"`      // 帖子ID
	AuthorId    int64  `json:"authorId"`    // 作者ID
	CommunityId int64  `json:"communityId"` // 社区ID
	Title       string `json:"title"`       // 帖子标题
	Content     string `json:"content"`     // 帖子内容
	CreateTime  string `json:"createTime"`  // 创建时间
	UpdatedTime string `json:"updatedTime"` // 更新时间
}

type PostDetail struct {
	AuthorInfo AuthorInfo `json:"authorInfo"`
	Post       Post       `json:"post"` // 帖子详情
	Community  Community  `json:"community"`
	VotedInfo  VotedInfo  `json:"votedInfo"`
}

type VotedInfo struct {
	UpCount   int64 `json:"upCount"`
	DownCount int64 `json:"downCount"`
}
