apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      {{- range .Values.ingress.paths }}
      - path: {{ .path }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .service }}
            port:
              number: {{ .port }}
      {{- end }}