apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingress.className }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  controller: k8s.io/ingress-nginx