apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-rpc-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
    app: user-rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-rpc
  template:
    metadata:
      labels:
        app: user-rpc
    spec:
      containers:
      - name: user-rpc
        image: {{ .Values.images.userRpc.repository }}:{{ .Values.images.userRpc.tag }}
        ports:
        - containerPort: {{ .Values.services.userRpc.port }}
        env:
        - name: ALIYUN_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.alicloud.name }}
              key: accessKeyId  # 使用固定的key名称
        - name: ALIYUN_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.alicloud.name }}
              key: accessKeySecret  # 使用固  
---
apiVersion: v1
kind: Service
metadata:
  name: user-rpc-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.userRpc.type }}
  selector:
    app: user-rpc
  ports:
    - protocol: TCP
      port: {{ .Values.services.userRpc.port }}
      targetPort: {{ .Values.services.userRpc.port }}
      nodePort: {{ .Values.services.userRpc.nodePort }}