// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	public "forum/app/vote/api/internal/handler/public"
	vote "forum/app/vote/api/internal/handler/vote"
	"forum/app/vote/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取帖子投票信息
				Method:  http.MethodGet,
				Path:    "/votes/:postId",
				Handler: public.GetVoteCountHandler(serverCtx),
			},
		},
		rest.WithPrefix("/vote/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 为帖子投票
				Method:  http.MethodPost,
				Path:    "/votes",
				Handler: vote.VotePostHandler(serverCtx),
			},
			{
				// 获取用户对帖子投票的记录
				Method:  http.MethodGet,
				Path:    "/votes/:postId/user/:userId",
				Handler: vote.GetUserVoteHandler(serverCtx),
			},
			{
				// 撤销用户对帖子的投票
				Method:  http.MethodDelete,
				Path:    "/votes/:postId/user/:userId",
				Handler: vote.RevokeVoteHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/vote/v1"),
	)
}
