// Code generated by goctl. DO NOT EDIT.
package types

type GetUserVoteReq struct {
	PostId int64 `path:"postId"` // 帖子ID
	UserId int64 `path:"userId"` // 用户ID
}

type GetUserVoteResp struct {
	VoteRecord VoteRecord `json:"voteRecord"` // 用户的投票记录
}

type GetVoteCountReq struct {
	PostId int64 `path:"postId"` // 帖子ID
}

type GetVoteCountResp struct {
	VoteCount VoteCount `json:"voteCount"` // 投票计数
}

type RevokeVoteReq struct {
	PostId int64 `path:"postId"` // 帖子ID
	UserId int64 `path:"userId"` // 用户ID
}

type RevokeVoteResp struct {
	Success bool `json:"success"` // 撤销投票是否成功
}

type VoteCount struct {
	PostId      int64  `json:"postId"`      // 帖子ID
	AgreeCount  int32  `json:"agreeCount"`  // 赞成票数
	OpposeCount int32  `json:"opposeCount"` // 反对票数
	CreateTime  string `json:"createTime"`  // 创建时间
	UpdatedTime string `json:"updatedTime"` // 更新时间
}

type VotePostReq struct {
	PostId   int64 `json:"postId"`   // 帖子ID
	VoteType int32 `json:"voteType"` // 投票类型 
}

type VotePostResp struct {
	Success bool `json:"success"` // 投票是否成功
}

type VoteRecord struct {
	VoteId      int64  `json:"voteId"`      // 投票记录ID
	PostId      int64  `json:"postId"`      // 帖子ID
	UserId      int64  `json:"userId"`      // 用户ID
	VoteType    int32  `json:"voteType"`    // 投票类型 0: 赞成票, 1: 反对票
	CreateTime  string `json:"createTime"`  // 创建时间
	UpdatedTime string `json:"updatedTime"` // 更新时间
}
