apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.alicloud.name }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
data:
  # 使用固定的 key 名称作为键
  accessKeyId: {{ .Values.secrets.alicloud.keys.accessKeyId }}
  accessKeySecret: {{ .Values.secrets.alicloud.keys.accessKeySecret }}
