apiVersion: v1
kind: Secret
metadata:
  name: find-endpoints-token
  annotations:
    kubernetes.io/service-account.name: {{ .Values.global.serviceAccount.name }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token