# mailhog-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:v1.0.1
        env:
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - name: http
          containerPort: 8025  # Web UI 端口
        - name: smtp
          containerPort: 1025  # SMTP 端口
---
# mailhog-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  selector:
    app: mailhog
  ports:
  - name: http
    port: 8025
    targetPort: 8025
  - name: smtp
    port: 1025
    targetPort: 1025
  type: ClusterIP