apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-api-deployment
  labels:
    app: comment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-api
  template:
    metadata:
      labels:
        app: comment-api
    spec:
      serviceAccount: find-endpoints
      containers:
      - name: comment-api
        image: morningeatdinner/comment-api:42d5b90
        ports:
        - containerPort: 8892
---
apiVersion: v1
kind: Service
metadata:
  name: comment-api-service
spec:
  selector:
    app: comment-api
  ports:
    - protocol: TCP
      port: 8892
      targetPort: 8892
      nodePort: 30892  # 添加nodePort端口,范围必须在30000-32767之间
  type: NodePort      # 将类型改为NodePort