apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-rpc-deployment
  labels:
    app: community-rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-rpc
  template:
    metadata:
      labels:
        app: community-rpc
      annotations:
        prometheus.io/scrape: "true"    # 放在 Pod template 的 annotations 中
        prometheus.io/port: "9091"      # 改成您实际暴露 metrics 的端口
    spec:
      containers:
      - name: community-rpc
        image: morningeatdinner/community-rpc:039d25c
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: community-rpc-service
spec:
  selector:
    app: community-rpc
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30002
  type: NodePort