apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqueue-deployment
  labels:
    app: mqueue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqueue
  template:
    metadata:
      labels:
        app: mqueue
      annotations:
        prometheus.io/scrape: "true"    # 放在 Pod template 的 annotations 中
        prometheus.io/port: "9091"      # 改成您实际暴露 metrics 的端口
    spec:
      serviceAccount: find-endpoints
      containers:
      - name: mqueue
        image: morningeatdinner/mqueue-job:039d25c
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: mqueue-service
spec:
  selector:
    app: mqueue
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP