apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-mq-deployment
  labels:
    app: post-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-mq
  template:
    metadata:
      labels:
        app: post-mq
    spec:
      containers:
      - name: post-mq
        image: morningeatdinner/post-mq:cfd59a0
        ports:
        - containerPort: 5001
        env:                                    # 添加环境变量配置
        - name: ALIYUN_ACCESS_KEY_ID           # 对应代码中的环境变量名
          valueFrom:
            secretKeyRef:
              name: ali-secret                 # Secret 的名称
              key: ALIYUN_ACCESS_KEY_ID        # Secret 中的键名
        - name: ALIYUN_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: ali-secret
              key: ALIYUN_ACCESS_KEY_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: post-mq-service
spec:
  selector:
    app: post-mq
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP