apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-rpc-deployment
  labels:
    app: post-rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-rpc
  template:
    metadata:
      labels:
        app: post-rpc
    spec:
      serviceAccount: find-endpoints
      containers:
      - name: post-rpc
        image: morningeatdinner/post-rpc:42d5b90
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: post-rpc-service
spec:
  selector:
    app: post-rpc
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30003
  type: NodePort