apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
    spec:
      serviceAccount: find-endpoints
      containers:
      - name: user-api
        image: morningeatdinner/user-api:039d25c
        ports:
        - containerPort: 8889
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/user-api   # 容器内的日志目录路径，根据实际应用的日志输出位置配置
      volumes:
      - name: log-volume
        hostPath:
          path: /var/log/pods/user-api   # 节点上的日志目录，建议按应用区分
          type: DirectoryOrCreate        # 如果目录不存在则创建
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 8889
      nodePort: 30889  # 添加nodePort端口,范围必须在30000-32767之间
  type: NodePort      # 将类型改为NodePort