apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-rpc-deployment
  labels:
    app: user-rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-rpc
  template:
    metadata:
      labels:
        app: user-rpc
    spec:
      containers:
      - name: user-rpc
        image: morningeatdinner/user-rpc:40c2bec
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: user-rpc-service
spec:
  selector:
    app: user-rpc
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001  # 添加nodePort端口,范围必须在30000-32767之间
  type: NodePort      # 将类型改为NodePort