apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-mq-deployment
  labels:
    app: vote-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-mq
  template:
    metadata:
      labels:
        app: vote-mq
      annotations:
        prometheus.io/scrape: "true"    # 放在 Pod template 的 annotations 中
        prometheus.io/port: "9091"      # 改成您实际暴露 metrics 的端口
    spec:
      serviceAccount: find-endpoints
      containers:
      - name: vote-mq
        image: morningeatdinner/vote-mq:039d25c
        ports:
        - containerPort: 5006
---
apiVersion: v1
kind: Service
metadata:
  name: vote-mq-service
spec:
  selector:
    app: vote-mq
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
  type: ClusterIP