// Code generated by goctl. DO NOT EDIT.
package types

type CaptchaReq struct {
}

type CaptchaResp struct {
	CaptchaId   string `json:"captchaId"`
	ImageBase64 string `json:"imageBase64"`
}

type CheckMobileReq struct {
	Phone string `json:"phone"`
}

type CheckMobileResp struct {
	Exist bool `json:"exist"`
}

type GetMobileCodeReq struct {
	Phone       string `json:"phone"`
	CaptchaId   string `json:"captchaId"`
	CaptchaCode string `json:"captchaCode"`
}

type GetMobileCodeResp struct {
}

type LoginReq struct {
	Username string `json:"username,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`
}

type RegisterReq struct {
	Phone           string `json:"phone,omitempty"`
	Code            string `json:"code,omitempty"`
	Name            string `json:"name"`
	Password        string `json:"password"`
	PasswordConfirm string `json:"password_confirm"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`
}

type UpdateEmailReq struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type UpdateEmailResp struct {
	User User `json:"user"`
}

type UpdateMobileReq struct {
	NewPhone string `json:"newPhone"`
	Code     string `json:"code"`
}

type UpdateMobileResp struct {
	User User `json:"user"`
}

type UpdatePasswordReq struct {
	OldPassword     string `json:"oldPassword"`
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type UpdatePasswordResp struct {
}

type UpdateUserInfoReq struct {
	Username     string `json:"username,optional"`
	City         string `json:"city,optional"`
	Introduction string `json:"introduction,optional"`
}

type UpdateUserInfoResp struct {
	User User `json:"user"`
}

type User struct {
	UserId       int64  `json:"userId"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	Phone        string `json:"phone,optional"`
	City         string `json:"city,optional"`
	Introduction string `json:"introduction,optional"`
	Avatar       string `json:"avatar,optional"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	User User `json:"user"`
}
