name: build

on:
  push:
    branches:
      - "main"

env:
  DOCKERHUB_USERNAME: morningeatdinner

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:      # Explicitly declaring permissions is a security best practice
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Useful for getting accurate Git history if needed
      
      - name: Set outputs
        id: vars
        # Using the newer GITHUB_OUTPUT syntax instead of deprecated set-output
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: pull goctl
        run: | 
          docker pull kevinwan/goctl
      
      - name: Create comment Dockerfile
        # Adding error handling and verification
        run: |
          # 确保工作目录存在并设置正确的权限
          sudo mkdir -p /workspace
          sudo chmod 777 /workspace
          docker run -v ${PWD}:/workspace -w /workspace kevinwan/goctl docker -go ./app/comment/api/comment.go
          if [ ! -f "./Dockerfile" ]; then
            echo "Dockerfile was not generated successfully"
            exit 1
          fi
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build backend and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/comment:${{ steps.vars.outputs.sha_short }}
            ${{ env.DOCKERHUB_USERNAME }}/comment:latest    # Adding latest tag
          cache-from: type=gha    # Utilizing GitHub Actions cache
          cache-to: type=gha,mode=max