// Code generated by goctl. DO NOT EDIT.
package types

type Comment struct {
	CommentId   int64  `json:"commentId"`   // 评论ID
	PostId      int64  `json:"postId"`      // 所属帖子ID
	AuthorId    int64  `json:"authorId"`    // 作者ID
	Content     string `json:"content"`     // 评论内容
	CreateTime  string `json:"createTime"`  // 创建时间
	UpdatedTime string `json:"updatedTime"` // 更新时间
}

type CreateCommentReq struct {
	PostId  int64  `json:"postId"`  // 所属帖子ID
	Content string `json:"content"` // 评论内容
}

type CreateCommentResp struct {
	Comment Comment `json:"comment"` // 创建的评论信息
}

type DeleteCommentReq struct {
	CommentId int64 `path:"commentId"` // 要删除的评论ID
}

type DeleteCommentResp struct {
}
