// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"forum/app/comment/rpc/internal/logic"
	"forum/app/comment/rpc/internal/svc"
	"forum/app/comment/rpc/pb"
)

type CommentServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCommentServiceServer
}

func NewCommentServiceServer(svcCtx *svc.ServiceContext) *CommentServiceServer {
	return &CommentServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建评论
func (s *CommentServiceServer) CreateComment(ctx context.Context, in *pb.CreateCommentRequest) (*pb.CreateCommentResponse, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

// 删除评论
func (s *CommentServiceServer) DeleteComment(ctx context.Context, in *pb.DeleteCommentRequest) (*pb.DeleteCommentResponse, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}
// 根据帖子ID获取评论
func (s *CommentServiceServer) GetCommentsByPost(ctx context.Context, in *pb.GetCommentsByPostRequest) (*pb.GetCommentsByPostResponse, error) {
	l := logic.NewGetCommentsByPostLogic(ctx, s.svcCtx)
	return l.GetCommentsByPost(in)
}
